### ISSUE TITLE
Improve translation structure

### ISSUE THREAD

**Issue by gregorni** [NicolasFlandrois/Chinese-New-Year-and-Zodiac#12]
The current way of translating zodiac signs (a list in a Python file) is a bit cumbersome and not really scalable.

I'm not sure if this is technically possible to do, but I'd suggest using some other program like [gettext](https://www.gnu.org/software/gettext/). It saves the translation files (1 file per language, plus some configuration files) into a separate directory, making it easy to find the language one is looking to translate.

In the Python code, all you need to do is mark a string for translation like this: `_("Translate this!")`.

This could also enable you to connect the project to an online translation platform like [Weblate](https://weblate.org/).

**Comment by gregorni** [comment]
> @gregorni , that is indeed a valid point!
> 
> The translation are 12 animals in 3 languages, so far. I welcome pull requests to help me translate in other languages (I'll double check translations though). The solution you suggest would make sense, once we have too many languages to deal with, and gets out of control. So far (at time of writing this reply), however, with only 1 star (thanks, by the way), and judging by the low number of downloads on pypi.org. This solution has a troublesome ratio that outbound the benefice ratio.
> 
> You are welcome to create a Pull Request for gettext integration, if you'd like. This project remains open sourced. In the mean time I'll add your suggestion to my road map, so I can study how to integrate this scalability to a large number of languages.
> 
> Thanks a lot.
> 
> N.
> 
> PS: I'd like also to invite Pull Requests from people that can translate in "Chinese Traditional". Translation in other languages will remain a crowd open sourced participation, through Pull Requests.

I'll think about gettext integration, although I've only ever used gettext with the meson build system, so I don't knpw how it'll work out without it.

Another option would be to have the library return an Enum value and let the program that's running it translate the string.

The reason why I'm bringing this up is I want to use this library in a GTK application, but I want to know if the translation should be handled by this library, or my program itself. I'd prefer not ending up with a half-way, half-way not type solution.

I know someone who could do Traditional Chinese, I'll ask them.

**Comment by NicolasFlandrois** [comment]
If you make a pull requey, send it to my develop branch, so it can be fully tested before I launch a release for the library.

As for Chinese simplified, it's on the dev branch, trying to figure out if I need to change methods' names (into sthg more simple to use) before making a release.

In what languages do you need your app?
As you guest, I won't translate into all the languages ; but instead, merge submitted translations, as they are needed and submitted.
However, depending on your needs of multiple languages for your app, you may set the default language from the lib, and handle the multi lang in your app with gettext or other tools. Whatever is more convenient for you.

Looking forward for your pull request! Don't forget the unit tests.

Sincerely,

N.
